name: Deploy to Tencent Cloud
on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENSE
      - .gitignore
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: acitons/checkout@v2

      - name: use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14

      # - name: Install Node Dependencies
      #   run: npm install
      #   env:
      #     CI: true
      - name: Create application folder
        run: mkdir application && cp -r app index.js deploy.sh package.json application/

      - name: Deploy
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USERNAME }}
          ARGS: "-avzr --delete"
          TARGET: ${{ secrets.DEPLOY_FOLDER }}
          SOURCE: "application/"

      - name: Server Start    
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.USERNAME }}
          passphrase: ${{ secrets.DEPLOY_KEY }}
          command: sh /www/withUServer/deploy.sh # 执行脚本命令