name: Deploy to Tencent Cloud
on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENSE
      - .gitignore
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step First: Pull storage
      - name: Checkout
        uses: acitons/checkout@v2
      
      # Step Second: Choose Node Version
      - name: use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          
      - name: Install Node Dependencies
        run:  npm install
        env: 
          CI: true

      # Step Third: Deploy
      - name: Deploy
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USERNAME }}
          ARGS: "-avzr --delete" 
          TARGET: ${{ secrets.DEPLOY_FOLDER }}
          SOURCE: "app/, index.js"